load("@prelude//:rules.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "game",
    package_name = "github.com/becker63/searchbench-go/internal/pure/game",
    srcs = ["game.go"],
    visibility = ["PUBLIC"],
)
