load("@prelude//:rules.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "treesitter",
    package_name = "github.com/becker63/searchbench-go/internal/adapters/codegraph/treesitter",
    srcs = [
        "doc.go",
        "errors.go",
        "index.go",
        "stub.go",
    ],
    deps = [
        "//src/searchbench-go/internal/pure/codegraph:codegraph",
        "//src/searchbench-go/internal/pure/domain:domain",
        "//src/searchbench-go/vendor/github.com/smacker/go-tree-sitter/golang:golang",
        "//src/searchbench-go/vendor/github.com/smacker/go-tree-sitter:go-tree-sitter",
    ],
    visibility = ["PUBLIC"],
)
