load("@prelude//:rules.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "importcheck",
    package_name = "github.com/becker63/searchbench-go/internal/testing/importcheck",
    srcs = ["importcheck.go"],
    visibility = ["PUBLIC"],
)
