load("@prelude//:rules.bzl", "go_binary")

go_binary(
    name = "searchbench",
    srcs = ["main.go"],
    deps = [
        "//src/searchbench-go/internal/surface/cli:cli",
    ],
    visibility = ["PUBLIC"],
)
