load("@prelude//:rules.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "reporoot",
    package_name = "github.com/becker63/searchbench-go/internal/testing/reporoot",
    srcs = ["reporoot.go"],
    visibility = ["PUBLIC"],
)
