load("@prelude//:rules.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "optimizer",
    package_name = "github.com/becker63/searchbench-go/internal/agents/optimizer",
    srcs = ["doc.go"],
    visibility = ["PUBLIC"],
)
