load("@prelude//:rules.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "pkl",
    package_name = "github.com/becker63/searchbench-go/internal/adapters/scoring/pkl",
    srcs = [
        "doc.go",
        "run.go",
    ],
    deps = [
        "//src/searchbench-go/internal/pure/score:score",
        "//src/searchbench-go/vendor/github.com/apple/pkl-go/pkl:pkl",
    ],
    visibility = ["PUBLIC"],
)
