load("@prelude//:rules.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "cli",
    package_name = "github.com/becker63/searchbench-go/internal/surface/cli",
    srcs = [
        "buck.go",
        "cli.go",
        "dataset.go",
        "doc.go",
        "run.go",
        "validate.go",
        "validate_bundle.go",
    ],
    deps = [
        "//src/searchbench-go/internal/adapters/bundle/fs:fs",
        "//src/searchbench-go/internal/adapters/config/pkl:pkl",
        "//src/searchbench-go/internal/adapters/dataset/lca:lca",
        "//src/searchbench-go/internal/app/round:round",
        "//src/searchbench-go/internal/pure/liveconfig:liveconfig",
        "//src/searchbench-go/internal/pure/report:report",
        "//src/searchbench-go/internal/surface/logging:logging",
        "//src/searchbench-go/vendor/github.com/alecthomas/kong:kong",
    ],
    visibility = ["PUBLIC"],
)
