load("@prelude//:rules.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "policy",
    package_name = "github.com/becker63/searchbench-go/internal/agents/evaluator/policy",
    srcs = ["evaluator.go"],
    deps = [
        "//src/searchbench-go/internal/adapters/config/pkl:pkl",
    ],
    visibility = ["PUBLIC"],
)

go_test(
    name = "policy_test",
    srcs = ["evaluator_test.go"],
    target_under_test = ":policy",
    deps = [
        "//src/searchbench-go/internal/adapters/config/pkl:pkl",
        "//src/searchbench-go/internal/agents/evaluator/fake:fake",
    ],
    labels = [
        "deterministic",
        "fast",
        "no-cgo",
        "unit",
    ],
)
