load("@prelude//:rules.bzl", "go_binary", "go_library", "go_test")

go_library(
    name = "testing",
    package_name = "github.com/becker63/searchbench-go/internal/testing",
    srcs = ["doc.go"],
    visibility = ["PUBLIC"],
)
