load("//build_defs:tool_ops.bzl", "npm_project_run", "npm_project_test")

npm_project_test(
    name = "check",
    npm_script = "docs:build",
)

npm_project_run(
    name = "site",
    npm_script = "docs:build",
)
